import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  ArrowLeft, User, Clock, Save, Phone, Mail, Calendar,
  Droplets, MapPin,
  MessageSquare, Trash2, ChevronRight, LogOut, CheckCircle,
  AlertTriangle, X,
} from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { profileAPI, chatHistoryAPI, consultationAPI } from '../api/client'
import { supabase } from './supabase'
import { useBreakpoint } from '../hooks/useBreakpoint'

/* ─── Chat session key (same as ChatPage) ─── */
const CHAT_SESSION_KEY = 'medivora_chat_session'

/**
 * Returns true when `phone` is a real Indian mobile number (+91XXXXXXXXXX or 10 digits).
 * Placeholder phones generated by _ensure_profile_and_patient() look like
 * "+91<uuid-hex-chars>" and will fail this check.
 */
function isRealPhone(phone) {
  if (!phone) return false
  const digits = phone.replace(/^\+91/, '').replace(/^91/, '').replace(/\D/g, '')
  return digits.length === 10
}

/* ─── Shared styles ─── */
const card = {
  background: '#ffffff', borderRadius: 16, border: '1px solid rgba(0,0,0,0.06)',
  padding: '20px 24px', marginBottom: 16,
}
const labelStyle = {
  fontSize: 12, fontWeight: 600, color: '#555555', marginBottom: 6, display: 'flex', alignItems: 'center', gap: 6,
}
const inp = {
  width: '100%', padding: '12px 14px', borderRadius: 10, fontSize: 14,
  border: '1.5px solid #d0daea', outline: 'none', background: '#ffffff',
  color: '#111111', fontFamily: 'var(--font)', boxSizing: 'border-box',
  transition: 'border-color 0.2s',
}
const inpDisabled = {
  ...inp, background: '#f5f8fc', color: '#888888', cursor: 'not-allowed',
}
const tabBtn = (active) => ({
  flex: 1, padding: '12px 0', fontSize: 14, fontWeight: 600, cursor: 'pointer',
  background: 'none', border: 'none', fontFamily: 'var(--font)',
  color: active ? '#1930AA' : '#999999',
  borderBottom: active ? '2.5px solid #1930AA' : '2.5px solid transparent',
  transition: 'all 0.2s',
})

export default function ProfileSettings() {
  const { isMobile } = useBreakpoint()
  const navigate = useNavigate()
  const { user, session, displayName, logout, getToken } = useAuth()
  const token = getToken ? getToken() : (session?.access_token || null)

  /* Detect signup method — email users have no `user.phone` */
  const isEmailUser = !(user?.phone)

  const [activeTab, setActiveTab] = useState('profile')

  // ─── Profile form state ────────────────────────────────────────
  const [form, setForm] = useState({
    first_name: '',
    last_name: '',
    email: '',
    phone: '',          // editable for email-signup users
    age: '',
    gender: '',
    blood_group: '',
    address: '',
    emergency_contact: '',
    medical_history: '',
    current_medications: '',
    allergies: '',
  })
  const [saving, setSaving] = useState(false)
  const [saveMsg, setSaveMsg] = useState('')
  const [loadingProfile, setLoadingProfile] = useState(true)

  // ─── Chat history state ────────────────────────────────────────
  const [sessions, setSessions] = useState([])
  const [selectedSession, setSelectedSession] = useState(null)
  const [sessionMessages, setSessionMessages] = useState([])
  const [loadingHistory, setLoadingHistory] = useState(false)

  // ─── Consultations state ───────────────────────────────────────
  const [consultations, setConsultations] = useState([])

  // ─── Load profile on mount ─────────────────────────────────────
  useEffect(() => {
    async function loadProfile() {
      setLoadingProfile(true)
      try {
        const userId = user?.id
        if (!userId || !token) { setLoadingProfile(false); return }

        const resp = await profileAPI.getProfile(userId, token)
        /* Backend returns { user: {...} } */
        const data = resp?.user || resp || {}

        /* Phone: for phone-signup users use auth phone; for email users use profiles.phone ONLY if it
           looks like a real number (not the +91<uuid-hex> placeholder). */
        const profilePhone = data.phone || ''
        const authPhone    = user?.phone || ''

        // Strip to 10 digits for the editable input
        const realProfileDigits = isRealPhone(profilePhone)
          ? profilePhone.replace(/^\+91/, '').replace(/^91/, '').replace(/\D/g, '')
          : ''

        setForm({
          first_name:          data.first_name || '',
          last_name:           data.last_name  || '',
          email:               data.email      || user?.email || '',
          /* Email users: show real phone if one was previously saved, otherwise blank */
          phone:               isEmailUser ? realProfileDigits : (authPhone || profilePhone),
          age:                 data.age != null ? String(data.age) : '',
          gender:              data.gender || '',
          blood_group:         data.blood_group || '',
          address:             data.address || '',
          emergency_contact:   data.emergency_contact || '',
          medical_history:     data.medical_history || '',
          current_medications: data.current_medications || '',
          allergies:           data.allergies || '',
        })
      } catch (err) {
        console.error('Failed to load profile:', err)
        /* Graceful fallback — pre-fill what we know from the auth token */
        const fallbackFirst = user?.user_metadata?.first_name || displayName?.split(' ')[0] || ''
        const fallbackLast  = user?.user_metadata?.last_name  || displayName?.split(' ')[1] || ''
        setForm(f => ({
          ...f,
          first_name: fallbackFirst,
          last_name:  fallbackLast,
          email:      user?.email || '',
        }))
      } finally {
        setLoadingProfile(false)
      }
    }
    loadProfile()
  }, [user, token]) // eslint-disable-line react-hooks/exhaustive-deps

  // ─── Load chat sessions + consultations when History tab opens ────
  useEffect(() => {
    if (activeTab !== 'history') return
    async function loadHistory() {
      setLoadingHistory(true)
      try {
        const userId = user?.id
        if (!userId || !token) return
        const [sessData, consultData] = await Promise.allSettled([
          chatHistoryAPI.getSessions(userId, token),
          consultationAPI.getMy(token),
        ])
        if (sessData.status === 'fulfilled') {
          const d = sessData.value
          setSessions(Array.isArray(d) ? d : d?.sessions || [])
        }
        if (consultData.status === 'fulfilled') {
          const d = consultData.value
          setConsultations(Array.isArray(d) ? d : d?.sessions || [])
        }
      } catch (err) {
        console.error('Failed to load history:', err)
      } finally {
        setLoadingHistory(false)
      }
    }
    loadHistory()
  }, [activeTab, user, token])

  // ─── Profile save handler ──────────────────────────────────────
  async function handleSave(e) {
    e.preventDefault()
    setSaving(true)
    setSaveMsg('')
    try {
      const userId = user?.id
      if (!userId || !token) throw new Error('Not authenticated')

      /* Build payload — include phone only for email-signup users */
      const payload = { ...form }
      if (!isEmailUser) {
        delete payload.phone   // phone-signup users cannot change phone
      } else if (payload.phone) {
        /* Normalise: strip leading zeros/spaces, add country code if needed */
        let p = payload.phone.replace(/\s+/g, '')
        if (p && !p.startsWith('+')) {
          p = p.startsWith('0') ? '+91' + p.slice(1) : '+91' + p
        }
        payload.phone = p
      }

      const resp = await profileAPI.updateProfile(userId, payload, token)
      const updFirst = resp?.user?.first_name || form.first_name || ''
      const updLast  = resp?.user?.last_name  || form.last_name  || ''
      const updatedName = (updFirst + ' ' + updLast).trim()
      setSaveMsg('✓ Profile updated successfully!')
      /* Update form with what the server echoed back */
      if (resp?.user) {
        const d = resp.user
        setForm(f => ({
          ...f,
          first_name:          d.first_name          || f.first_name,
          last_name:           d.last_name           || f.last_name,
          email:               d.email               || f.email,
          age:                 d.age != null ? String(d.age) : f.age,
          gender:              d.gender              || f.gender,
          blood_group:         d.blood_group         || f.blood_group,
          address:             d.address             || f.address,
          emergency_contact:   d.emergency_contact   || f.emergency_contact,
          medical_history:     d.medical_history     || f.medical_history,
          current_medications: d.current_medications || f.current_medications,
          allergies:           d.allergies           || f.allergies,
        }))
      }
      /* Propagate name change to Supabase auth metadata so displayName
         updates everywhere in the app (header, sidebar initials, etc.) */
      if (updatedName) {
        await supabase.auth.updateUser({ data: { full_name: updatedName, first_name: updFirst, last_name: updLast } })
      }
      setTimeout(() => setSaveMsg(''), 4000)
    } catch (err) {
      setSaveMsg('Error: ' + (err.message || 'Could not save profile'))
    } finally {
      setSaving(false)
    }
  }

  // ─── Load session messages ─────────────────────────────────────
  async function openSession(sess) {
    setSelectedSession(sess)
    try {
      const data = await chatHistoryAPI.getHistory(sess.session_id || sess.id, token)
      setSessionMessages(Array.isArray(data) ? data : data?.messages || [])
    } catch (err) {
      console.error('Failed to load messages:', err)
      setSessionMessages([])
    }
  }

  // ─── Delete session ────────────────────────────────────────────
  async function handleDeleteSession(sessionId, e) {
    e.stopPropagation()
    if (!window.confirm('Delete this chat session?')) return
    try {
      await chatHistoryAPI.deleteSession(sessionId, token)
      setSessions(prev => prev.filter(s => (s.session_id || s.id) !== sessionId))
      if ((selectedSession?.session_id || selectedSession?.id) === sessionId) {
        setSelectedSession(null)
        setSessionMessages([])
      }
    } catch (err) {
      console.error('Failed to delete session:', err)
    }
  }

  // ─── Logout — clear chat history then sign out ─────────────────
  function handleLogout() {
    sessionStorage.removeItem(CHAT_SESSION_KEY)
    logout()
    navigate('/login')
  }

  // ─── Delete account ────────────────────────────────────────────
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [deleteConfirm,   setDeleteConfirm]   = useState('')
  const [deleting,        setDeleting]        = useState(false)
  const [deleteError,     setDeleteError]     = useState('')

  async function handleDeleteAccount() {
    if (deleteConfirm !== 'DELETE') return
    setDeleting(true); setDeleteError('')
    try {
      await profileAPI.deleteAccount(token)
      sessionStorage.removeItem(CHAT_SESSION_KEY)
      await logout()
      navigate('/', { replace: true })
    } catch (err) {
      setDeleteError(err.message || 'Failed to delete account. Please try again.')
      setDeleting(false)
    }
  }

  /* ── Helpers ── */
  // Build a display-safe phone: only show if it's actually a real 10-digit number
  const rawPhone = user?.phone || ''
  const phoneDisplay = isRealPhone(rawPhone)
    ? '+91 ' + rawPhone.replace(/^\+91/, '').replace(/^91/, '').replace(/\D/g, '')
    : null
  const fullNameDisplay = (form.first_name + ' ' + form.last_name).trim() || displayName || ''
  const avatarInitial = (fullNameDisplay || 'U').charAt(0).toUpperCase()

  return (
    <div style={{ height: '100%', minHeight: 0, overflow: 'auto', background: '#f5f8fc', fontFamily: 'var(--font)' }}>

      <div style={{ maxWidth: 640, margin: '0 auto', padding: isMobile ? '16px 12px' : '24px 16px' }}>
        <button onClick={() => navigate('/chat')} type="button" style={{
          background: 'none', border: 'none', cursor: 'pointer', display: 'inline-flex',
          alignItems: 'center', gap: 6, color: '#1930AA', fontWeight: 600, fontSize: 13,
          fontFamily: 'var(--font)', padding: '0 0 16px',
        }}>
          <ArrowLeft size={16} /> Back to Chat
        </button>

        {/* Profile avatar + name header */}
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <div style={{
            width: 72, height: 72, borderRadius: '50%', margin: '0 auto 12px',
            background: 'linear-gradient(135deg, #1930AA, #00AFEF)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            boxShadow: '0 4px 20px rgba(25,48,170,0.2)',
          }}>
            <span style={{ color: '#ffffff', fontSize: 28, fontWeight: 700 }}>{avatarInitial}</span>
          </div>
          <h2 style={{ fontSize: 20, fontWeight: 800, color: '#111111', margin: 0 }}>
            {fullNameDisplay || 'Your Profile'}
          </h2>
          <p style={{ fontSize: 13, color: '#888888', marginTop: 4 }}>
            {phoneDisplay
              ? phoneDisplay
              : user?.email
              ? user.email
              : 'Manage your account'}
          </p>
        </div>

        {/* Tabs */}
        <div style={{ display: 'flex', borderBottom: '1px solid #e0eaf8', marginBottom: 20 }}>
          <button style={tabBtn(activeTab === 'profile')} onClick={() => setActiveTab('profile')}>
            <User size={14} style={{ marginRight: 6, verticalAlign: 'middle' }} />
            Profile
          </button>
          <button style={tabBtn(activeTab === 'history')} onClick={() => setActiveTab('history')}>
            <Clock size={14} style={{ marginRight: 6, verticalAlign: 'middle' }} />
            History
          </button>
        </div>

        {/* ══════════════ PROFILE TAB ══════════════ */}
        {activeTab === 'profile' && (
          <>
            {loadingProfile ? (
              <div style={{ textAlign: 'center', padding: 40, color: '#999999' }}>Loading profile…</div>
            ) : (
              <>
              <form onSubmit={handleSave}>

                {/* Personal Information */}
                <div style={card}>
                  <h3 style={{ fontSize: 15, fontWeight: 700, color: '#111111', marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
                    <User size={16} color="#1930AA" /> Personal Information
                  </h3>

                  {/* First Name + Last Name */}
                  <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 12, marginBottom: 14 }}>
                    <div style={{ flex: 1 }}>
                      <label style={labelStyle}><User size={12} /> First Name</label>
                      <input
                        style={inp}
                        value={form.first_name}
                        onChange={e => setForm({ ...form, first_name: e.target.value })}
                        placeholder="First name"
                        onFocus={e => e.target.style.borderColor = '#1930AA'}
                        onBlur={e => e.target.style.borderColor = '#d0daea'}
                      />
                    </div>
                    <div style={{ flex: 1 }}>
                      <label style={labelStyle}><User size={12} /> Last Name</label>
                      <input
                        style={inp}
                        value={form.last_name}
                        onChange={e => setForm({ ...form, last_name: e.target.value })}
                        placeholder="Last name"
                        onFocus={e => e.target.style.borderColor = '#1930AA'}
                        onBlur={e => e.target.style.borderColor = '#d0daea'}
                      />
                    </div>
                  </div>

                  {/* Phone — editable for email users, read-only for phone users */}
                  <div style={{ marginBottom: 14 }}>
                    <label style={labelStyle}>
                      <Phone size={12} />
                      Phone Number
                      {isEmailUser && (
                        <span style={{ fontSize: 10, color: '#00AFEF', fontWeight: 500, marginLeft: 4 }}>
                          (add your number)
                        </span>
                      )}
                    </label>
                    {isEmailUser ? (
                      <>
                        <div style={{ position: 'relative', display: 'flex', alignItems: 'center' }}>
                          <span style={{
                            position: 'absolute', left: 14, fontSize: 13, color: '#555', fontWeight: 600,
                            userSelect: 'none', pointerEvents: 'none',
                          }}>+91</span>
                          <input
                            style={{ ...inp, paddingLeft: 48 }}
                            type="tel"
                            value={form.phone}
                            onChange={e => setForm({ ...form, phone: e.target.value.replace(/\D/g, '').slice(0, 10) })}
                            placeholder="10-digit mobile number"
                            maxLength={10}
                            onFocus={e => e.target.style.borderColor = '#1930AA'}
                            onBlur={e => e.target.style.borderColor = '#d0daea'}
                          />
                        </div>
                        <p style={{ fontSize: 11, color: '#aaa', marginTop: 4 }}>
                          Enter your 10-digit mobile number for appointment reminders
                        </p>
                      </>
                    ) : (
                      <>
                        <input style={inpDisabled} value={phoneDisplay || ''} disabled readOnly />
                        <p style={{ fontSize: 11, color: '#aaa', marginTop: 4 }}>Phone number cannot be changed</p>
                      </>
                    )}
                  </div>

                  {/* Email */}
                  <div style={{ marginBottom: 14 }}>
                    <label style={labelStyle}><Mail size={12} /> Email</label>
                    <input
                      style={inp}
                      type="email"
                      value={form.email}
                      onChange={e => setForm({ ...form, email: e.target.value })}
                      placeholder="your@email.com"
                      onFocus={e => e.target.style.borderColor = '#1930AA'}
                      onBlur={e => e.target.style.borderColor = '#d0daea'}
                    />
                  </div>

                  {/* Age + Gender */}
                  <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 12, marginBottom: 14 }}>
                    <div>
                      <label style={labelStyle}><Calendar size={12} /> Age</label>
                      <input
                        style={inp}
                        type="number"
                        min="0"
                        max="150"
                        value={form.age}
                        onChange={e => setForm({ ...form, age: e.target.value })}
                        placeholder="Age"
                        onFocus={e => e.target.style.borderColor = '#1930AA'}
                        onBlur={e => e.target.style.borderColor = '#d0daea'}
                      />
                    </div>
                    <div>
                      <label style={labelStyle}>Gender</label>
                      <select
                        style={inp}
                        value={form.gender}
                        onChange={e => setForm({ ...form, gender: e.target.value })}
                      >
                        <option value="">Select</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="other">Other</option>
                        <option value="prefer_not_to_say">Prefer not to say</option>
                      </select>
                    </div>
                  </div>

                  {/* Blood Group */}
                  <div style={{ marginBottom: 14 }}>
                    <label style={labelStyle}><Droplets size={12} /> Blood Group</label>
                    <select
                      style={inp}
                      value={form.blood_group}
                      onChange={e => setForm({ ...form, blood_group: e.target.value })}
                    >
                      <option value="">Select blood group</option>
                      {['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map(bg => (
                        <option key={bg} value={bg}>{bg}</option>
                      ))}
                    </select>
                  </div>

                  {/* Address */}
                  <div>
                    <label style={labelStyle}><MapPin size={12} /> Address</label>
                    <textarea
                      style={{ ...inp, minHeight: 60, resize: 'vertical' }}
                      value={form.address}
                      onChange={e => setForm({ ...form, address: e.target.value })}
                      placeholder="Your address"
                      onFocus={e => e.target.style.borderColor = '#1930AA'}
                      onBlur={e => e.target.style.borderColor = '#d0daea'}
                    />
                  </div>
                </div>

                {/* Save feedback */}
                {saveMsg && (
                  <div style={{
                    padding: '10px 14px', borderRadius: 10, marginBottom: 12, fontSize: 13,
                    display: 'flex', alignItems: 'center', gap: 8,
                    background: saveMsg.startsWith('Error') ? 'rgba(255,61,0,0.07)' : 'rgba(0,200,83,0.07)',
                    border: '1px solid ' + (saveMsg.startsWith('Error') ? 'rgba(255,61,0,0.18)' : 'rgba(0,200,83,0.18)'),
                    color: saveMsg.startsWith('Error') ? '#d93a00' : '#00a040',
                  }}>
                    {!saveMsg.startsWith('Error') && <CheckCircle size={14} />}
                    {saveMsg}
                  </div>
                )}

                {/* Save button */}
                <button
                  type="submit"
                  disabled={saving}
                  style={{
                    width: '100%', padding: '14px 0', borderRadius: 12, fontSize: 15, fontWeight: 700,
                    border: 'none', background: 'linear-gradient(135deg, #1930AA, #00AFEF)',
                    color: '#ffffff', cursor: saving ? 'wait' : 'pointer',
                    fontFamily: 'var(--font)', opacity: saving ? 0.7 : 1, marginBottom: 12,
                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
                  }}
                >
                  <Save size={16} /> {saving ? 'Saving…' : 'Save Profile'}
                </button>

                {/* Logout */}
                <button
                  type="button"
                  onClick={handleLogout}
                  style={{
                    width: '100%', padding: '13px 0', borderRadius: 12, fontSize: 14, fontWeight: 600,
                    border: '1.5px solid rgba(255,61,0,0.2)', background: 'rgba(255,61,0,0.04)',
                    color: '#d93a00', cursor: 'pointer', fontFamily: 'var(--font)',
                    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
                    marginBottom: 24,
                  }}
                >
                  <LogOut size={15} /> Log Out
                </button>

                {/* ── Delete account ── */}
                <div>
                  <button
                    type="button"
                    onClick={() => { setShowDeleteModal(true); setDeleteConfirm(''); setDeleteError('') }}
                    style={{
                      padding: '10px 20px', borderRadius: 9, fontSize: 13, fontWeight: 700,
                      border: '1.5px solid rgba(255,61,0,0.3)', background: 'rgba(255,61,0,0.06)',
                      color: '#d93a00', cursor: 'pointer', fontFamily: 'var(--font)',
                      display: 'flex', alignItems: 'center', gap: 6, transition: 'background 0.2s',
                    }}
                    onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,61,0,0.12)'}
                    onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,61,0,0.06)'}
                  >
                    <Trash2 size={13} /> Delete My Account
                  </button>
                </div>
              </form>

              {/* ── Delete confirmation modal ── */}
              {showDeleteModal && (
                <div style={{ position: 'fixed', inset: 0, zIndex: 500, background: 'rgba(0,0,0,0.45)', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 }}>
                  <div style={{ background: '#ffffff', borderRadius: 16, padding: isMobile ? '20px 16px' : '28px', width: '100%', maxWidth: isMobile ? 'calc(100vw - 32px)' : 420, boxShadow: '0 12px 40px rgba(0,0,0,0.2)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        <AlertTriangle size={18} color='#d93a00' />
                        <span style={{ fontSize: 16, fontWeight: 700, color: '#111' }}>Delete Account</span>
                      </div>
                      <button onClick={() => setShowDeleteModal(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 4 }}>
                        <X size={18} color='#888' />
                      </button>
                    </div>

                    <div style={{ padding: '12px 14px', borderRadius: 10, background: 'rgba(255,61,0,0.06)', border: '1px solid rgba(255,61,0,0.15)', marginBottom: 16 }}>
                      <p style={{ fontSize: 13, color: '#d93a00', fontWeight: 600, margin: '0 0 6px' }}>This will permanently:</p>
                      <ul style={{ margin: 0, paddingLeft: 16 }}>
                        {['Delete your profile and personal information', 'Remove your medical records and chat history', 'Cancel any pending consultations', 'This action cannot be reversed'].map((t, i) => (
                          <li key={i} style={{ fontSize: 12, color: '#555', marginBottom: 3 }}>{t}</li>
                        ))}
                      </ul>
                    </div>

                    <label style={{ display: 'block', fontSize: 13, fontWeight: 600, color: '#333', marginBottom: 8 }}>
                      Type <strong>DELETE</strong> to confirm
                    </label>
                    <input
                      type="text"
                      value={deleteConfirm}
                      onChange={e => setDeleteConfirm(e.target.value)}
                      placeholder="Type DELETE"
                      autoFocus
                      style={{ width: '100%', padding: '11px 14px', borderRadius: 10, border: `1.5px solid ${deleteConfirm === 'DELETE' ? '#d93a00' : '#d0daea'}`, outline: 'none', fontFamily: 'var(--font)', fontSize: 14, boxSizing: 'border-box', marginBottom: 6, color: '#111' }}
                    />

                    {deleteError && (
                      <p style={{ fontSize: 12, color: '#d93a00', marginBottom: 10 }}>{deleteError}</p>
                    )}

                    <div style={{ display: 'flex', gap: 10, marginTop: 16 }}>
                      <button
                        type="button"
                        onClick={() => setShowDeleteModal(false)}
                        style={{ flex: 1, padding: '12px 0', borderRadius: 10, border: '1.5px solid #d0daea', background: '#fff', color: '#666', cursor: 'pointer', fontFamily: 'var(--font)', fontSize: 14, fontWeight: 600 }}
                      >
                        Cancel
                      </button>
                      <button
                        type="button"
                        onClick={handleDeleteAccount}
                        disabled={deleteConfirm !== 'DELETE' || deleting}
                        style={{
                          flex: 1, padding: '12px 0', borderRadius: 10, border: 'none',
                          background: deleteConfirm === 'DELETE' ? '#d93a00' : '#f0d0ca',
                          color: '#fff', cursor: deleteConfirm === 'DELETE' && !deleting ? 'pointer' : 'not-allowed',
                          fontFamily: 'var(--font)', fontSize: 14, fontWeight: 700,
                          display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6,
                          opacity: deleting ? 0.7 : 1, transition: 'background 0.2s',
                        }}
                      >
                        <Trash2 size={14} /> {deleting ? 'Deleting…' : 'Delete Account'}
                      </button>
                    </div>
                  </div>
                </div>
              )}
              </>
            )}
          </>
        )}

        {/* ══════════════ HISTORY TAB ══════════════ */}
        {activeTab === 'history' && (
          <>
            {loadingHistory ? (
              <div style={{ textAlign: 'center', padding: 40, color: '#999999' }}>Loading history…</div>
            ) : selectedSession ? (
              /* ── Session detail view ── */
              <div>
                <button
                  onClick={() => { setSelectedSession(null); setSessionMessages([]) }}
                  style={{
                    background: 'none', border: 'none', cursor: 'pointer', display: 'flex',
                    alignItems: 'center', gap: 6, color: '#1930AA', fontWeight: 600, fontSize: 13,
                    fontFamily: 'var(--font)', padding: 0, marginBottom: 16,
                  }}
                >
                  <ArrowLeft size={14} /> Back to sessions
                </button>

                <div style={card}>
                  <h3 style={{ fontSize: 14, fontWeight: 700, color: '#111111', marginBottom: 4 }}>Chat Session</h3>
                  <p style={{ fontSize: 12, color: '#888888', marginBottom: 16 }}>
                    {selectedSession.created_at
                      ? new Date(selectedSession.created_at).toLocaleDateString('en-IN', {
                          day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit',
                        })
                      : 'Unknown date'}
                    {selectedSession.message_count ? ' · ' + selectedSession.message_count + ' messages' : ''}
                  </p>

                  {sessionMessages.length === 0 ? (
                    <p style={{ fontSize: 13, color: '#aaa', textAlign: 'center', padding: 20 }}>No messages found</p>
                  ) : (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                      {sessionMessages.map((msg, i) => {
                        const isAi = msg.sender === 'ai' || msg.sender === 'assistant' || msg.role === 'assistant'
                        return (
                          <div key={i} style={{
                            padding: '10px 14px', borderRadius: 12, fontSize: 13, lineHeight: 1.65,
                            background: isAi ? '#f5f8fc' : 'rgba(25,48,170,0.06)',
                            borderLeft: '3px solid ' + (isAi ? '#00AFEF' : '#1930AA'),
                          }}>
                            <p style={{ fontSize: 10, fontWeight: 700, marginBottom: 4, color: isAi ? '#00AFEF' : '#1930AA', textTransform: 'uppercase', letterSpacing: 0.5 }}>
                              {isAi ? 'Medivora AI' : 'You'}
                            </p>
                            <p style={{ color: '#333333', margin: 0, whiteSpace: 'pre-wrap' }}>
                              {msg.content || msg.message || msg.text || ''}
                            </p>
                          </div>
                        )
                      })}
                    </div>
                  )}
                </div>
              </div>
            ) : (
              /* ── History list ── */
              <div>

                {/* ── Consultations section ── */}
                <p style={{ fontSize: 12, fontWeight: 700, color: '#555555', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 10 }}>
                  Consultations
                </p>
                {consultations.length === 0 ? (
                  <div style={{ ...card, textAlign: 'center', padding: '24px 20px', marginBottom: 24 }}>
                    <Calendar size={28} color="#d0daea" style={{ marginBottom: 10 }} />
                    <p style={{ fontSize: 13, color: '#999999' }}>No consultations yet</p>
                  </div>
                ) : (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 24 }}>
                    {consultations.map((c, i) => {
                      const topic    = c.patient_note || c.specialty || 'Consultation'
                      const specialty = (c.specialty || '').replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
                      const dateStr  = (c.scheduled_at || c.created_at) ? new Date(c.scheduled_at || c.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }) : ''
                      const statusColor = c.status === 'completed' ? '#00a040'
                        : c.status === 'scheduled' ? '#1930AA'
                        : (c.status === 'cancelled' || c.status === 'no_show') ? '#d93a00'
                        : '#f59e0b'
                      const statusLabel = c.status === 'scheduled' ? 'Confirmed'
                        : c.status === 'completed' ? 'Completed'
                        : (c.status === 'cancelled' || c.status === 'no_show') ? 'Cancelled'
                        : 'Requested'
                      return (
                        <div
                          key={c.id || i}
                          onClick={() => navigate('/consultations')}
                          style={{
                            ...card, marginBottom: 0, cursor: 'pointer',
                            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                            transition: 'border-color 0.2s',
                          }}
                          onMouseEnter={e => e.currentTarget.style.borderColor = 'rgba(25,48,170,0.2)'}
                          onMouseLeave={e => e.currentTarget.style.borderColor = 'rgba(0,0,0,0.06)'}
                        >
                          <div style={{ flex: 1, minWidth: 0 }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                              <Calendar size={14} color="#1930AA" />
                              <span style={{ fontSize: 13, fontWeight: 600, color: '#111111', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                                {topic}
                              </span>
                            </div>
                            <div style={{ display: 'flex', gap: 12, fontSize: 11, color: '#999999', flexWrap: 'wrap' }}>
                              {dateStr && <span>{dateStr}</span>}
                              {specialty && <span style={{ color: '#00AFEF' }}>{specialty}</span>}
                              <span style={{
                                padding: '1px 6px', borderRadius: 4, fontSize: 10, fontWeight: 600,
                                background: statusColor + '18', color: statusColor,
                              }}>{statusLabel}</span>
                            </div>
                          </div>
                          <ChevronRight size={16} color="#cccccc" style={{ flexShrink: 0, marginLeft: 8 }} />
                        </div>
                      )
                    })}
                  </div>
                )}

                {/* ── Chat sessions section ── */}
                <p style={{ fontSize: 12, fontWeight: 700, color: '#555555', textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 10 }}>
                  Chat Sessions
                </p>
                {sessions.length === 0 ? (
                  <div style={{ ...card, textAlign: 'center', padding: '40px 20px' }}>
                    <MessageSquare size={36} color="#d0daea" style={{ marginBottom: 12 }} />
                    <p style={{ fontSize: 15, fontWeight: 600, color: '#555555', marginBottom: 6 }}>No chat history yet</p>
                    <p style={{ fontSize: 13, color: '#999999' }}>Start a conversation with Medivora to see your history here</p>
                  </div>
                ) : (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {sessions.map((sess) => {
                      const sid = sess.session_id || sess.id
                      const date = sess.created_at ? new Date(sess.created_at) : null
                      return (
                        <div
                          key={sid}
                          onClick={() => openSession(sess)}
                          style={{
                            ...card, marginBottom: 0, cursor: 'pointer', display: 'flex',
                            alignItems: 'center', justifyContent: 'space-between', transition: 'border-color 0.2s',
                          }}
                          onMouseEnter={e => e.currentTarget.style.borderColor = 'rgba(0,175,239,0.3)'}
                          onMouseLeave={e => e.currentTarget.style.borderColor = 'rgba(0,0,0,0.06)'}
                        >
                          <div style={{ flex: 1, minWidth: 0 }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                              <MessageSquare size={14} color="#1930AA" />
                              <span style={{ fontSize: 13, fontWeight: 600, color: '#111111' }}>
                                {sess.title || sess.topic || 'Chat Session'}
                              </span>
                            </div>
                            <div style={{ display: 'flex', gap: 12, fontSize: 11, color: '#999999' }}>
                              {date && <span>{date.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</span>}
                              {sess.message_count && <span>{sess.message_count} messages</span>}
                              {sess.status && (
                                <span style={{
                                  padding: '1px 6px', borderRadius: 4, fontSize: 10, fontWeight: 600,
                                  background: sess.status === 'active' ? 'rgba(0,200,83,0.1)' : 'rgba(0,0,0,0.04)',
                                  color: sess.status === 'active' ? '#00a040' : '#999999',
                                }}>{sess.status}</span>
                              )}
                            </div>
                          </div>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                            <button
                              onClick={(e) => handleDeleteSession(sid, e)}
                              title="Delete session"
                              style={{ background: 'none', border: 'none', cursor: 'pointer', padding: 4, color: '#cccccc', transition: 'color 0.2s' }}
                              onMouseEnter={e => e.currentTarget.style.color = '#d93a00'}
                              onMouseLeave={e => e.currentTarget.style.color = '#cccccc'}
                            >
                              <Trash2 size={14} />
                            </button>
                            <ChevronRight size={16} color="#cccccc" />
                          </div>
                        </div>
                      )
                    })}
                  </div>
                )}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}
